### ISSUE TITLE
bk-808

### ISSUE THREAD

**Issue by krissgren** [blemasle/arduino-sim808#10]
Hi,
I have that board: [LINK](https://cdn.instructables.com/ORIG/FAO/80RU/IXLALERK/FAO80RUIXLALERK.pdf)
I connected only GND,PWRIN,TR,RX to arduino.
On my serial monitor I have only:
`Waiting for echo...
-->AT`
if I connect sim808 directly to serial port on my laptop, and send "AT" command, the board response "OK".

Please help me :)

**Comment by blemasle** [comment]
Hi,

The library inits the connection with the SIM808 by sending a reset pulse on the `RST` pin. `SIM808` class only has constructors involving the `RST` pin. Which constructor are you using ? 

It seems the `RST` pin is not wired on board so the library might need another round of modification to support that use case.

**Comment by blemasle** [comment]
Hi.

Did you come with a solution ? I was really surprised to see that you're board do not have the `RST` pin wired as it is a fairly common way of driving the SIM808 boot. Have you tried to just comment out [lines 11, 16 and 27](https://github.com/blemasle/arduino-sim808/blob/master/src/SIM808.cpp#L11) and see if it works by any chance ?

**Comment by JoanMCD** [comment]
here is a code special for the bk-808. So direct pins support. 
https://github.com/mcore1976/sim808gpstracker

Also, the default BAUD rate of the BK-808 is 9600.

BR

**Comment by JoanMCD** [comment]
Problems: 
- In the AcquireGPSPosition.ino the define FIX_GPS_DELAY is missing
- For the bk-808 on USB I suggest a 100uF C on the 3.3V of the module
- Deactivate the reset() and in waitForReady() the while (waitResponse(TO_F(TOKEN_RDY)) != 0); (I got never a RDY from the bk-808)

**Comment by blemasle** [comment]
Hi @JoanMCD 

`FIX_GPS_DELAY` is not missing, see https://github.com/blemasle/arduino-sim808/blob/master/examples/AcquireGPSPosition/AcquireGPSPosition.ino#L27 . Could you elaborate please ?  

The call to `reset()` is here for compatibility with other codes/previous actions done on the sim808 which can disrupt the communication with the chip from the library (eg setting echo to off). I've seen previous cases of various libraries being broken because users set their SIM808 in a particular configuration that prevent initialization. The `reset()` is meant to circumvent such cases and can be disabled if needed.  
I however don't think I'll do it in the library as the default option as the initialization sequence has proved itself reliable in continuous use for 10 months on a custom board with full access to the SIM808 chip (which this library was build for). It also reinforces boot up sequences for circuitry that can turn the sim808 on/off. I'm open to the same sort of configuration option as the `power` and `reset` pin of course, provided that it can be tested on circuitry other than mine.  

As for the `RDY`, I think you never got it because your using autobauding (as per the datasheet, `RDY` will not be sent in such cases). In the case of the library, and according to the datasheet, that `while (waitResponse(TO_F(TOKEN_RDY)) != 0);` shouldn't be necessary and could indeed causes troubles. I'm surprised it's working at all. But by experience, I know that the datasheet for the SIM808 are inaccurate and unreliable :/

**Comment by JoanMCD** [comment]
HI @blemasle, thx for your reply. It's more my Log how to get the BK808 running at first and info for other BK-808 users. I have corrected my message above. The explanation of RDY and autobauding sounds well - I never read the datasheet or configure the module - I follow the Arduino style and take a fresh module and a library in the hope it isn't necessary :)
PS: I like your "while - waitResponse - SIMCOMAT_DEFAULT_TIMEOUT" implementation !

**Comment by JoanMCD** [comment]
the KEX pin on the BK-808 is hard shorted to GND by R104 - I have replaced it to a 10k value.  Without signal it acts as ever, by pulling up a power cycle can be triggerd. 

```
void SIM808::reset()
{
	if(_pwrKeyPin != SIM808_UNAVAILABLE_PIN)digitalWrite(_pwrKeyPin, HIGH); //pwr off
	delay(1500); //wait discharching capacitors
	if(_pwrKeyPin != SIM808_UNAVAILABLE_PIN)digitalWrite(_pwrKeyPin, LOW); //pwr on
	delay(500); //wait charching capacitors
}
```
